const { MessageEmbed } = require("discord.js");

module.exports = {
  name: 'svlink',
  aliases: ['serverlinks', 'links'],
  cat: 'owner',
  ownerPermit: true,  // Owner only command
  run: async (client, message, args) => {
    // Check if the user is the bot owner
    if (message.author.id !== client.config.ownerId) return;

    let links = [];

    // Loop through all guilds to generate invite links
    for (const guild of client.guilds.cache.values()) {
      try {
        const invite = await guild.invites.create(guild.channels.cache.first(), { maxAge: 0, maxUses: 0 });
        links.push(`[${guild.name}](${invite.url})`);
      } catch (err) {
        // If there is an error creating the invite, skip it
        links.push(`${guild.name}: Unable to create invite`);
      }
    }

    // Create an embed with the invite links
    const svLinkEmbed = new MessageEmbed()
      .setTitle('Server Invite Links')
      .setColor('#2f3136')
      .setDescription(links.join("\n"))
      .setFooter('Generated by YGamer');

    // Send the embed message
    message.channel.send({ embeds: [svLinkEmbed] });
  }
};